#!/usr/bin/env bash
#script to install nginx on the server
#nginx should listen to port 80
#when queried using curl(GET) must return "hello world"
#can't use systemct1 to restart nginx

sudo apt-get -y update

#command to install
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
