#!/usr/bin/env bash
#i created my domain from .tech using the free access
#the domain has an A recird configured to my server
#then uploaded to my intranet profile

#name of my created domain
abasay.tech