#!/usr/bin/env bash
# configures a new HAproxy as a load balancer using roundrobin

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend abasay.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 121835-web-01 100.26.175.38:80
        server 121835-web-02 54.237.2.239:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
