#!/usr/bin/env bash
#bash script to fix container to run nginx as nginx and run on port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
