#!/usr/bin/env bash
# reload gunicorn gracefully
if pgrep gunicorn >/dev/null 2>&1; then
    gunicorn_pid=$(pgrep gunicorn)

    # Send a graceful reload signal to Gunicorn
    echo "Reloading Gunicorn..."
    kill -HUP "$gunicorn_pid"
    echo "Gunicorn reloaded."
else
    echo "Gunicorn is not running."
fi
